title:            André Ribas
description:      Desenvolvedor Web focado em Frontend construindo o Frontend de Sites e Aplicativos Web.
url:              https://ar.dev.br
permalink:        pretty
timezone:         America/Sao_Paulo
kramdown:
  hard_wrap: true
sass:
  sass_dir: assets
  style: :compressed
collections:
  notes:
    output: false
  pages:
    output: true
